---
abstract: 'Moo wrapper for queued downloads via Net::Curl & AnyEvent'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  Test::Exception: 0
  Test::Warn: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Net-Curl-Queued
recommends:
  EV: 4.11
  JSON::XS: 0
requires:
  AnyEvent: 0
  HTTP::Response: 0
  JSON: 0
  Moo: 1.001000
  MooX::Types::MooseLike: 0.18
  Net::Curl: 0.25
  URI: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/creaktive/AnyEvent-Net-Curl-Queued/issues
  homepage: https://github.com/creaktive/AnyEvent-Net-Curl-Queued
  repository: git://github.com/creaktive/AnyEvent-Net-Curl-Queued.git
version: 0.046
