---
abstract: 'Any::Moose wrapper for queued downloads via Net::Curl & AnyEvent'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  Test::HTTP::AnyEvent::Server: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300026, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Net-Curl-Queued
requires:
  Mouse::Util::TypeConstraints: 0
  MouseX::NativeTraits: 0
  MouseX::NonMoose: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/creaktive/AnyEvent-Net-Curl-Queued/issues
  homepage: https://github.com/creaktive/AnyEvent-Net-Curl-Queued
  repository: git://github.com/creaktive/AnyEvent-Net-Curl-Queued.git
version: 0.031
